language: node_js

node_js:
  - stable

install:
  yarn install

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

script:
  - yarn test-ci
